name: Grading

# Sự kiện kích hoạt workflow
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest --junitxml=results.xml

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.xml
